version: '3'

services:
  app:
    build: .
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./:/go/app
    ports:
      - 1323:1323
      - 2345:2345
    expose:
      - 2345
    #command: ./app
    command: ./app
    #command: dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec ./server
    depends_on:
      - mongodb
    networks:
      - api-net
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - 27017:27017
    expose:
      - 27017
    command: mongod --logpath=/dev/null # --quiet
    networks:
      - api-net
networks:
  api-net:
    driver: bridge
volumes:
  mongo-data: #volume needs to be linked to mongodata for write permissions to work